version: "3"
services:
  customerservice:
    image: rabbithole/rabbitshop:customerservice
    # image: customerservice
    deploy:
      # replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      # restart_policy:
      #   condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
  mongo:
    image: mongo
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - ./mongo-data:/data
    ports:
      - "27017:27017"
    networks:
      - webnet
  # visualizer:
  #   image: dockersamples/visualizer:stable
  #   deploy:
  #     placement:
  #       constraints: [node.role == manager]
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   ports:
  #     - "9001:8080"
  #   networks:
  #     - webnet
networks:
  webnet:
